# Generated by Django 4.0.4 on 2023-01-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
